### ISSUE TITLE
System support

### ISSUE THREAD

**Issue by lavrenkov-sketch** [jerryuhoo/Masked-Face-Recognition#1]
This project support only Windows?
is it possible to get examples of how face recognition works with masked people

**Comment by jerryuhoo** [comment]
Sorry for the late reply cuz I was busy working on my other projects. It may not be helpful for you since it has been a long time, but it may help someone who find this project in the future. 
1. I haven't test on MacOS, and I use a function that calls the webcam of my surface pro. If this function doesn't support Mac webcam, maybe it is helpful to find other functions.
2. There's a lot you can improve this project since I only combined mask detection and face recognition(without mask). It is possible to recognized the id of the person who wears mask, though the recognition rate is much lower than without mask. Maybe you can crop the part between head and nose (above mask), then train the model, or you can train the model with both masked or unmasked faces (just add an AI-generated mask on the face, I saw some datasets did this to generate masked faces).
